kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: chaos-testing
  name: account-default-viewer-zfhpn
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-default-viewer-zfhpn
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["chaos-mesh.org"]
  resources: [ "*", "*/*"]
  verbs: ['get', 'list', 'watch', 'create', 'delete', 'patch', 'update']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-default-viewer-zfhpn
subjects:
- kind: ServiceAccount
  name: account-default-viewer-zfhpn
  namespace: chaos-testing
roleRef:
  kind: ClusterRole
  name: role-default-viewer-zfhpn
  apiGroup: rbac.authorization.k8s.io
